### PR TITLE
Added processes to handle quantity

### PR DESCRIPTION
**Pull request by scrable**
Added getIdentifierCount() so I can loop through all identifiers in
report.cpp without using the real value of identifierCount.

Added loops for adding books if the ISBN matches. The project
description says ISBNs are unique, so I am searching for matching ISBNs.

Reorganized some statements and assignments depending on if the ISBN
entered is unique.

Made ISBN be the first variable entered to check against current ISBNs
to avoid entering useless information.

Clear screens and user interaction for these new things will be added
later.

Added a way to list items with their quantity in report.cpp. This will
be rearranged into the appropriate methods  that need the quantity
later.

### CODE REVIEW

**Comment by ahouts** [comment]
Making this change to books this late into the project would have serious implications. The cashier module already assumes that books can have the same ISBN, the database files that are created will not contain the count variable, and the addbook, removebook, changebook all no longer work if this change is made. If we are going to make this change we are going to have to change almost every function in the entire project. If this is necessary to get the report module to work then we should go for it, but if at all possible, we should avoid it.

**Comment by scrable** [comment]
I'll try to find some other way then, but I don't really think there's another way considering the ISBNs are supposed to be unique.

**Comment by ahouts** [comment]
If you go to the main page of the project and click on branch right under the number of commits and switch to the report_test module, try downloading that branch as a zip and trying out the thing I put together. 

It goes through the database, finds all of the books with the same ISBN and counts them, then lists how many copies of each book with a specific ISBN there are.

**Comment by ahouts** [comment]
I will admit it is nearly impossible to follow what is going on in the code.

**Comment by scrable** [comment]
Alright I'll try it, give me a minute.

**Comment by scrable** [comment]
I might be able to do it with this. I'll get back to you soon.

**Comment by ahouts** [comment]
alright cool :)

**Comment by scrable** [comment]
The only issue I'm having is getting the title to print correctly.

http://i.imgur.com/OFH6Cbv.png

I had to comment out your method of printing the title because it was displaying these errors:
http://i.imgur.com/fJ8NyDx.png

With just books[i].getTitle() it prints the same title repeatedly.

I'm not quite sure how to get your method to work but if I can figure it out it should be ok.

**Comment by ahouts** [comment]
hmm... I don't know why that is  happening...
capture

image from the report_test branch

**Comment by scrable** [comment]
Let me copy everything over and try again.

**Comment by ahouts** [comment]
alright. it looks like it doesn't know what kind of object database is for some reason. It might be one of those weird bugs that happens for no reason and reformatting the code changes it...

**Comment by scrable** [comment]
I cant even build it with a fresh copy, getting the same errors.

**Comment by ahouts** [comment]
let me try

**Comment by ahouts** [comment]
It might be one of the project settings in visual studio. I just downloaded it and it compiled just fine using VS 2015...

**Comment by scrable** [comment]
I'll try it on my laptop then, that has 2015. Give me a few minutes.

**Comment by ahouts** [comment]
alright

**Comment by scrable** [comment]
Yeah it compiles on my laptop in 2015, not sure what the problem is on 2013.

**Comment by ahouts** [comment]
We will have to solve that eventually because it needs to run on VS2013.

**Comment by ahouts** [comment]
On Tuesday in class I will port it to VS2013 so it works on the school computers. For now it will probably be easier to go with what works.

**Comment by ahouts** [comment]
It is also worth mentioning that a data leak occurs if there are more than 128 copies of a book. With the method I used. We might want to change line 175 from 128 to 1024 just to be on the safe side, even if it does waste a lot of memory.

**Comment by scrable** [comment]
The exe will work without having 2015, but does he try to compile the code himself on 2013? If he doesn't compile it then it won't be an issue, but if he does then we'll have to fix it. I assume he will compile but I don't know.

**Comment by ahouts** [comment]
Actually the EXE only works on computers that have that version of visual studio installed. I tired this yesterday on a different computer.

**Comment by ahouts** [comment]
It is possible to create a universal exe though, and we should do that

**Comment by ahouts** [comment]
Oh yeah me and travis are in a chat room, use this link on something with a mic 
https://discord.gg/maduin-sentry-flash

**Pull request merged**
